apiVersion: v1
kind: DeploymentConfig
metadata:
  name: topological-inventory-ingress-api
spec:
  replicas: 1
  selector:
    name: topological-inventory-ingress-api
  template:
    metadata:
      name: topological-inventory-ingress-api
      labels:
        name: topological-inventory-ingress-api
    spec:
      containers:
      - name: topological-inventory-ingress-api
        image: topological-inventory-ci/topological-inventory-ingress-api:latest
        ports:
        - containerPort: 4567
        readinessProbe:
          tcpSocket:
            port: 4567
        env:
        - name: QUEUE_HOST
          value: topological-inventory-kafka
        - name: QUEUE_PORT
          value: "9092"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - topological-inventory-ingress-api
        from:
          kind: ImageStreamTag
          name: topological-inventory-ingress-api:latest
