apiVersion: v1
kind: Service
metadata:
  name: topological-inventory-ingress-api
  labels:
    app: topological-inventory
spec:
  ports:
  - name: topological-inventory-ingress-api
    port: 3000
    targetPort: 3000
  selector:
    name: topological-inventory-ingress-api
