apiVersion: v1
kind: DeploymentConfig
metadata:
  name: persister
spec:
  replicas: 1
  selector:
    name: persister
  template:
    metadata:
      name: persister
      labels:
        name: persister
    spec:
      containers:
      - name: persister
        image: topological-inventory-ci/persister:latest
        env:
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: database-password
        - name: DATABASE_NAME
          value: topological_inventory_production
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_PORT
          value: "5432"
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: query-api-secrets
              key: encryption-key
        - name: QUEUE_HOST
          value: kafka
        - name: QUEUE_PORT
          value: 9092
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - persister
        from:
          kind: ImageStreamTag
          name: persister:latest
