apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topological-inventory-postgresql
  labels:
    app: topological-inventory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
