apiVersion: v1
kind: Template
labels:
  template: topological-inventory-database-secrets
metadata:
  name: topological-inventory-database-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: topological-inventory-database-secrets
  stringData:
    database-password: "${DATABASE_PASSWORD}"
parameters:
- name: DATABASE_PASSWORD
  displayName: PostgreSQL Password
  required: true
  description: Password for the PostgreSQL user.
  from: "[a-zA-Z0-9]{8}"
  generate: expression
