apiVersion: v1
kind: Service
metadata:
  name: topological-inventory-postgresql
  labels:
    app: topological-inventory
spec:
  ports:
  - name: topological-inventory-postgresql
    port: 5432
    targetPort: 5432
  selector:
    name: topological-inventory-postgresql
