apiVersion: v1
kind: Service
metadata:
  name: topological-inventory-kafka
spec:
  ports:
  - name: topological-inventory-kafka
    port: 9092
  - name: topological-inventory-zookeeper
    port: 2181
  selector:
    name: topological-inventory-kafka
