apiVersion: v1
kind: DeploymentConfig
metadata:
  name: query-api
spec:
  replicas: 1
  selector:
    name: query-api
  template:
    metadata:
      name: query-api
      labels:
        name: query-api
    spec:
      containers:
      - name: query-api
        image: topological-inventory-ci/query-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: database-password
        - name: DATABASE_NAME
          value: topological_inventory_production
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_PORT
          value: "5432"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: query-api-secrets
              key: secret-key
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: query-api-secrets
              key: encryption-key
        readinessProbe:
          tcpSocket:
            port: 3000
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - query-api
        from:
          kind: ImageStreamTag
          name: query-api:latest
